mutation ($mediaId: Int, $progress: Int, $status: MediaListStatus) {
    SaveMediaListEntry (mediaId: $mediaId, progress: $progress, status: $status) {
        id
        title
        score
        progress
        status
  }
}
